version: "3.7"

services:
  db:
    image: postgres:11-alpine
    env_file:
      - build/docker.env
    ports:
      - "6432:5432"

  backend:
    depends_on:
      - db
      - d-transformer
      - u-transformer
    build:
      context: ./
      dockerfile: build/Dockerfile-dev

    entrypoint: sh -c './build/wait-for db:5432 -- go run -mod=vendor main.go'

    ports:
      - "8080:8080"
    env_file:
      - build/docker.env
    environment:
      - JOBS_DB_HOST=db
  d-transformer:
    build:
      context: ../rudder-transformer/
      dockerfile: Dockerfile
    ports:
      - "9090:9090"

  u-transformer:
    build:
      context: ../rudder-transformer/
      dockerfile: Dockerfile-ut
    ports:
      - "9191:9191"
